# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-pNZplOt08kWyX0Uyc9iBkVuEa0kfcA
"""

import panda as pd

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
from pandas import DataFrame

from IPython.display import Image
from IPython.core.display import HTML